name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*" # Will trigger only if tag is pushed matching pattern `v*` (Eg: `v0.1.0`)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get lowercase repository name
        id: lower-repo
        run: |
          echo "::set-output name=repository::$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: false
          tags: docker.pkg.github.com/${{ steps.lower-repo.outputs.repository }}/automatisch:latest

      - name: Login to GitHub Packages
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push docker.pkg.github.com/${{ steps.lower-repo.outputs.repository }}/automatisch:latest